### ISSUE TITLE
All clusters re-synched every run "security context does not match the current one"

### ISSUE THREAD

**Issue by bootc** [zalando/postgres-operator#1383]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s (via RKE)
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

All database clusters are restarted at every "resync interval" because of the following reason:

```
time="2021-02-24T20:30:36Z" level=info msg="reason: new statefulset containers's postgres (index 0) security context does not match the current one" cluster-name=netbox/netbox-postgres pkg=cluster
```

I've noticed that in version 1.6.0 the `postgres` container's securityContext looks like this:
```
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
```

But in 1.6.1 the same container's securityContext is:
```
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
```

I'd be happy to provide further details, please let me know what you need.

**Comment by mboutet** [comment]
I think this is the same as https://github.com/zalando/postgres-operator/issues/1377. A fix has been committed but it is not released yet.

**Comment by caiconkhicon** [comment]
@bootc : I somehow get the same issue. In my case, setting `spilo_privileged: true` fixes the issue (please note that it requires you to create a PodSecurityPolicy named `privileged`). It is also a new thing in 1.6.1 (https://github.com/zalando/postgres-operator/pull/1326/files)

Besides, I also see this log on Spilo pods: `seteuid: Operation not permitted`. Do you also have it?

**Comment by kirillka415** [comment]
I have checked new version of postgres-operator and have the same issue.
I was used latest copy from master  branch.
setting spilo_privileged: true wasn't solved the issue in my case.

Here my manifest 
```
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "acid-pg-dbcluster"
  namespace: "default"
  labels:
    team: acid
spec:
  teamId: "acid"
  postgresql:
    version: "12"
  numberOfInstances: 3 
  volume:
    size: "2Gi"
  preparedDatabases:
    mydb: {}
  allowedSourceRanges:
    # IP ranges to access your cluster go here 
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
```
I see the following events when do describe of postgresql 

> kubectl describe postgresql acid-pg-dbcluster

```
Status:
  Postgres Cluster Status:  SyncFailed
Events:
  Type     Reason  Age                 From               Message
  ----     ------  ----                ----               -------
  Normal   Update  28m (x30 over 14h)  postgres-operator  Performing rolling update
  Warning  Sync    17m (x22 over 10h)  postgres-operator  could not sync cluster: could not sync statefulsets: could not recreate pods: could not recreate replica pod "default/acid-pg-dbcluster-2": pod label wait timeout
```

Here is log of postgres-operator 
> time="2021-03-02T04:23:45Z" level=info msg="SYNC event has been queued" cluster-name=default/acid-pg-dbcluster pkg=controller worker=0
> time="2021-03-02T04:23:45Z" level=info msg="there are 1 clusters running" pkg=controller
> time="2021-03-02T04:23:45Z" level=info msg="syncing of the cluster started" cluster-name=default/acid-pg-dbcluster pkg=controller worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="team API is disabled" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=info msg="syncing secrets" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="secret default/postgres.acid-pg-dbcluster.credentials.postgresql.acid.zalan.do already exists, fetching its password" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="secret default/standby.acid-pg-dbcluster.credentials.postgresql.acid.zalan.do already exists, fetching its password" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="syncing master service" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="syncing replica service" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="No load balancer created for the replica service" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="syncing volumes using \"pvc\" storage resize mode" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=info msg="volume claims do not require changes" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="syncing statefulsets" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="cached StatefulSet value exists, rollingUpdate flag is false" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=info msg="found a statefulset with an unfinished rolling update of the pods" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="Generating Spilo container, environment variables" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="[{SCOPE acid-pg-dbcluster nil} {PGROOT /home/postgres/pgdata/pgroot nil} {POD_IP  &EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:status.podIP,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}} {POD_NAMESPACE  &EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}} {PGUSER_SUPERUSER postgres nil} {KUBERNETES_SCOPE_LABEL cluster-name nil} {KUBERNETES_ROLE_LABEL spilo-role nil} {PGPASSWORD_SUPERUSER  &EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:&SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:postgres.acid-pg-dbcluster.credentials.postgresql.acid.zalan.do,},Key:password,Optional:nil,},}} {PGUSER_STANDBY standby nil} {PGPASSWORD_STANDBY  &EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:&SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:standby.acid-pg-dbcluster.credentials.postgresql.acid.zalan.do,},Key:password,Optional:nil,},}} {PAM_OAUTH2 https://info.example.com/oauth2/tokeninfo?access_token= uid realm=/employees nil} {HUMAN_ROLE zalandos nil} {PGVERSION 12 nil} {KUBERNETES_LABELS {\"application\":\"spilo\"} nil} {SPILO_CONFIGURATION {\"postgresql\":{},\"bootstrap\":{\"initdb\":[{\"auth-host\":\"md5\"},{\"auth-local\":\"trust\"}],\"users\":{\"zalandos\":{\"password\":\"\",\"options\":[\"CREATEDB\",\"NOLOGIN\"]}},\"dcs\":{}}} nil} {DCS_ENABLE_KUBERNETES_API true nil} {AZURE_STORAGE_ACCESS_KEY  &EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:&SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:postgres-pod-secrets,},Key:AZURE_STORAGE_ACCESS_KEY,Optional:nil,},}} {AZURE_STORAGE_ACCOUNT  &EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:&SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:postgres-pod-secrets,},Key:AZURE_STORAGE_ACCOUNT,Optional:nil,},}} {BACKUP_NUM_TO_RETAIN 3 nil} {BACKUP_SCHEDULE 0 */12 * * * nil} {CLONE_AZURE_STORAGE_ACCESS_KEY  &EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:&SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:postgres-pod-secrets,},Key:CLONE_AZURE_STORAGE_ACCESS_KEY,Optional:nil,},}} {CLONE_AZURE_STORAGE_ACCOUNT  &EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:&SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:postgres-pod-secrets,},Key:CLONE_AZURE_STORAGE_ACCOUNT,Optional:nil,},}} {CLONE_USE_WALG_BACKUP true nil} {CLONE_USE_WALG_RESTORE true nil} {CLONE_WALE_BACKUP_THRESHOLD_PERCENTAGE 100 nil} {CLONE_WALG_AZ_PREFIX azure://dev-postgresql-backup/walg-folder/$(CLONE_SCOPE) nil} {CLONE_WALG_DISABLE_S3_SSE true nil} {CLONE_WALG_DOWNLOAD_CONCURRENCY 1 nil} {USE_WALG_BACKUP true nil} {USE_WALG_RESTORE true nil} {WALE_BACKUP_THRESHOLD_PERCENTAGE 100 nil} {WALG_AZ_PREFIX azure://dev-postgresql-backup/walg-folder/$(SCOPE) nil} {WALG_DISABLE_S3_SSE true nil} {WALG_DOWNLOAD_CONCURRENCY 1 nil}]" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="set statefulset's rolling update annotation to true: caller/reason from cache" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=info msg="statefulset default/acid-pg-dbcluster is not in the desired state and needs to be updated" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="-          terminationMessagePath: /dev/termination-log," cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="-          terminationMessagePolicy: File," cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="-      restartPolicy: Always," cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="-      dnsPolicy: ClusterFirst," cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="-      serviceAccount: postgres-pod," cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="-      securityContext: {}," cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="-      schedulerName: default-scheduler" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="+      securityContext: {}" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="-      kind: PersistentVolumeClaim," cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="-      apiVersion: v1," cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="-      status: {" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="-        phase: Pending" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="-      }" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="+      status: {}" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="-  }," cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="-  revisionHistoryLimit: 10" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="+  }" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=info msg="reason: new statefulset containers's postgres (index 0) security context does not match the current one" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="updating statefulset" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="patching statefulset annotations" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="patching statefulset annotations" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="performing rolling update" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=info msg="there are 3 pods in the cluster to recreate" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="name=acid-pg-dbcluster-0 phase=Running ip=10.1.4.16" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="name=acid-pg-dbcluster-1 phase=Running ip=10.1.4.53" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="name=acid-pg-dbcluster-2 phase=Running ip=10.1.4.54" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:23:45Z" level=debug msg="subscribing to pod \"default/acid-pg-dbcluster-1\"" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:24:17Z" level=info msg="pod \"default/acid-pg-dbcluster-1\" has been recreated" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:24:17Z" level=debug msg="unsubscribing from pod \"default/acid-pg-dbcluster-1\" events" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:24:17Z" level=debug msg="subscribing to pod \"default/acid-pg-dbcluster-2\"" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:34:27Z" level=debug msg="unsubscribing from pod \"default/acid-pg-dbcluster-2\" events" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:34:27Z" level=warning msg="error while syncing cluster state: could not sync statefulsets: could not recreate pods: could not recreate replica pod \"default/acid-pg-dbcluster-2\": pod label wait timeout" cluster-name=default/acid-pg-dbcluster pkg=cluster worker=0
> time="2021-03-02T04:34:27Z" level=error msg="could not sync cluster: could not sync statefulsets: could not recreate pods: could not recreate replica pod \"default/acid-pg-dbcluster-2\": pod label wait timeout" cluster-name=default/acid-pg-dbcluster pkg=controller worker=0

**Comment by caiconkhicon** [comment]
@kirillka415 : a note is that setting up `spilo_privileged: true` requires you to also create a PSP with the name `privileged` with enough permission

**Comment by kirillka415** [comment]
@caiconkhicon 
Thank you for pointing that I need to create a PSP with the name privileged.
I am  using  helm cart  and thought it will be enough to set  just ```spilo_privileged: true``` in values.yaml and upgrade the chart.  
Could you please provide me example of yaml manifest  to create PSP?

**Comment by caiconkhicon** [comment]
@kirillka415 : I do not have my code here, but please try:
`apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  privileged: true`

**Comment by kirillka415** [comment]
Thanks @caiconkhicon 
I created PodSecurityPolicy with "privileged" using following example below, but still having the same issue 
https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/policy/privileged-psp.yaml

Anyway, it should work without ```spilo_privileged: true```, shouldn't it?

**Comment by caiconkhicon** [comment]
@kirillka415 : It is quite confusing but I will try to explain (and hope my understanding is correct): it should, if you do not use PSP in your cluster (that means all Pods just have full permission). Please note that before v1.6.1, the Operator is always told to use the PSP named "privileged", so if that PSP does not exist, the "default psp" - normally means full permission, is used. In my case, because I use Rancher, so if I do not specify and create the "privileged" PSP, the "default psp" from Rancher does not give enough permission.

**Comment by arsiesys** [comment]
Hello, it seems really similar to this issue, I did found a workaround for my case and posted on the following:
https://github.com/zalando/postgres-operator/issues/1390

**Comment by FxKu** [comment]
You can also use the operator image with the following tag: `v1.6.1-2-gca968ca1`. It contains the fix. Sorry for the inconvenience. Slipped through as we had the SYS_NICE capability defined in our infra and e2e tests also only covers this scenario. We could have done another release but in the meantime other important features got merged, too, which we are testing atm. But next release will come soon.

**Comment by FxKu** [comment]
Bugfix release is out
