### ISSUE TITLE
Logical Backup fails with Version 17

### ISSUE THREAD

**Issue by Rohmilchkaese** [zalando/postgres-operator#2917]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** ghcr.io/zalando/postgres-operator:v1.14.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** K8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report / question

We do WAL Backups to S3 and also logical backups. 
It does work for us with Postgres 14 - 16. We set up a Postgres Version 17 server lately and logical Backups to S3 seem broken. 

Anyone else experienced something similar? 

Some general remarks when posting a bug report:
```
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9 IPv4                                                                                                                                                                                                  
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9 API Endpoint: https://172.30.136.1:443/api/v1                                                                                                                                                         
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                                       
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9                                  Dload  Upload   Total   Spent    Left  Speed                                                                                                                         
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100 20203    0 20203    0     0   605k      0 --:--:-- --:--:-- --:--:--  636k                                          
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                                       
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9                                  Dload  Upload   Total   Spent    Left  Speed                                                                                                                         
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100 32408    0 32408    0     0  1408k      0 --:--:-- --:--:-- --:--:-- 1438k                                          
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9 + '[' s3 == az ']'                                                                                                                                                                                    
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9 + dump                                                                                                                                                                                                
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9 + /usr/lib/postgresql/17/bin/pg_dumpall                                                                                                                                                               
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9 + compress                                                                                                                                                                                            
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9 + pigz                                                                                                                                                                                                
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9 + upload                                                                                                                                                                                              
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9 + case $LOGICAL_BACKUP_PROVIDER in                                                                                                                                                                    
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9 /dump.sh: line 40: /usr/lib/postgresql/17/bin/pg_dumpall: No such file or directory                                                                                                                   
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9 ++ estimate_size                                                                                                                                                                                      
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9 ++ /usr/lib/postgresql/17/bin/psql -tqAc 'select sum(pg_database_size(datname)::numeric) from pg_database;'                                                                                           
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9 /dump.sh: line 35: /usr/lib/postgresql/17/bin/psql: No such file or directory                                                                                                                         
logical-backup-open-webui-db-cluster-manual-bp6-7tlv9 /dump.sh: line 134: / DUMP_SIZE_COEFF: syntax error: operand expected (error token is "/ DUMP_SIZE_COEFF")                                                                                            
stream closed EOF for postgres-cluster/logical-backup-open-webui-db-cluster-manual-bp6-7tlv9 (logical-backup)                                                                                                                                               
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc IPv4                                                                                                                                                                                                  
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc API Endpoint: https://172.30.136.1:443/api/v1                                                                                                                                                         
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                                       
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc                                  Dload  Upload   Total   Spent    Left  Speed                                                                                                                         
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100 20203    0 20203    0     0   767k      0 --:--:-- --:--:-- --:--:--  789k                                          
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                                       
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc                                  Dload  Upload   Total   Spent    Left  Speed                                                                                                                         
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100 32408    0 32408    0     0  1363k      0 --:--:-- --:--:-- --:--:-- 1376k                                          
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc + '[' s3 == az ']'                                                                                                                                                                                    
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc + dump                                                                                                                                                                                                
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc + /usr/lib/postgresql/17/bin/pg_dumpall                                                                                                                                                               
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc + compress                                                                                                                                                                                            
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc + upload                                                                                                                                                                                              
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc + pigz                                                                                                                                                                                                
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc + case $LOGICAL_BACKUP_PROVIDER in                                                                                                                                                                    
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc /dump.sh: line 40: /usr/lib/postgresql/17/bin/pg_dumpall: No such file or directory                                                                                                                   
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc ++ estimate_size                                                                                                                                                                                      
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc ++ /usr/lib/postgresql/17/bin/psql -tqAc 'select sum(pg_database_size(datname)::numeric) from pg_database;'                                                                                           
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc /dump.sh: line 35: /usr/lib/postgresql/17/bin/psql: No such file or directory                                                                                                                         
logical-backup-open-webui-db-cluster-manual-bp6-4l8wc /dump.sh: line 134: / DUMP_SIZE_COEFF: syntax error: operand expected (error token is "/ DUMP_SIZE_COEFF") 
```

**Comment by Rohmilchkaese** [comment]
@jjungnickel thanks! Indeed the CRDS seems outdated. 
Strage thing: 
If i manually deploy it, the current is visible. 
But whenever the Postgres Operator gets restarted it seems like the old version of the CRD gets deployed again. And that defaults to not the latest Version of the Backup Image 
`ghcr.io/zalando/postgres-operator/logical-backup:v1.13.0`

But the CRDS in the newest Version seems to be
`ghcr.io/zalando/postgres-operator/logical-backup:v1.14.0`

Which makes a lot of sense since it correlates with the version of the Operator and the UI. 

So at this point i dont know? Maybe dig to find out where the CRDS in the wrong version come? Deployed is Version 1.14 of the Operator ofc. But CRDS just seem off. But not that I ever remember caring about those tbh.

**Comment by Rohmilchkaese** [comment]
@jjungnickel thanks for your input. I did the following. Fixed in the helm values of the operator. 

```
        configLogicalBackup:
          #####
          #####
          #####
          # image used for backups
          logical_backup_docker_image: "ghcr.io/zalando/postgres-operator/logical-backup:v1.14.0"
```
So that solved it. 

But the crd still has: 
```
                  logical_backup_docker_image:                                                                                                                                                                                                              
                    Default:  ghcr.io/zalando/postgres-operator/logical-backup:v1.13.0                                                                                                                                                                      
                    Type:     string        
```

So a little strange still but i guess i have to life with that if i dont want to go down a rabbit hole. Most importantly: backups works! 

Thanks for pointing me in the right direction

**Comment by FxKu** [comment]
Guess we can close this. Thanks for helping each other 🤝

**Comment by paulkre** [comment]
It's still wrong here:
https://github.com/zalando/postgres-operator/blob/51135b07db0fb81f5fe5e6f2eab1d4d894f64cd4/charts/postgres-operator/crds/operatorconfigurations.yaml#L513
