### ISSUE TITLE
Environment set by pod_environment_configmap not used in restore_script.sh

### ISSUE THREAD

**Issue by IlyaSemenov** [zalando/postgres-operator#550]
## Steps to reproduce

Run postgres operator with `pod_environment_configmap` setting custom S3-compatible storage credentials:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
spec:
  selector:
    matchLabels:
      app: postgres-operator
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: postgres-operator
    spec:
      serviceAccountName: zalando-postgres-operator
      containers:
      - name: postgres-operator
        image: registry.opensource.zalan.do/acid/smoke-tested-postgres-operator:v1.1.0-8-g0b53dbe
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
          limits:
            cpu: 2000m
            memory: 500Mi
        env:
        - name: CONFIG_MAP_NAME
          value: postgres-operator

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-operator
data:
  enable_master_load_balancer: "false"
  enable_pod_antiaffinity: "true"
  enable_teams_api: "false"
  docker_image: registry.opensource.zalan.do/acid/spilo-cdp-11:1.5-p72
  pod_environment_configmap: "postgres-pod-env"
  wal_s3_bucket: "foo-postgres-wal"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-pod-env
data:
  AWS_ACCESS_KEY_ID: xxx
  AWS_SECRET_ACCESS_KEY: yyy
  AWS_ENDPOINT: https://hb.bizmrg.com
  # for /scripts/wal-e-wal-fetch.sh
  S3_HOST: hb.bizmrg.com
  # Bypass get_provider() and force PROVIDER_LOCAL
  DEVELOP: "1"
```

## Expected result

WAL is pushed and then restored from S3 bucket at bizmrg.

## Actual result

WAL is pushed to bizmrg correctly. However when restoring a failed database, postgres restore script tries to pulls from AWS S3, not from bizmrg S3. `S3_HOST` is empty when `/scripts/restore_command.sh` is called, and is then set to incorrect value at https://github.com/zalando/spilo/blob/f15e8e36aba694ae60c2765b8c99a687e0493889/postgres-appliance/scripts/wal-e-wal-fetch.sh#L85-L87

The only environment that is used by restore script comes from `/home/postgres/etc/wal-e.d/env`:

```console
# cd /home/postgres/etc/wal-e.d/env; for i in *; do echo $i=$(cat $i); done
AWS_ACCESS_KEY_ID=xxx
AWS_ENDPOINT=https://hb.bizmrg.com
AWS_REGION=loca
AWS_SECRET_ACCESS_KEY=yyy
TMPDIR=/home/postgres/pgdata/tmp
WALE_LOG_DESTINATION=stderr
WALE_S3_ENDPOINT=https+path://hb.bizmrg.com:443
WALE_S3_PREFIX=s3://foo-postgres-wal/spilo/foo-db/7291fe3c-64f1-11e9-a240-525400a0c459/wal/
WALG_DOWNLOAD_CONCURRENCY=2
WALG_S3_PREFIX=s3://foo-postgres-wal/spilo/foo-db/7291fe3c-64f1-11e9-a240-525400a0c459/wal/
WALG_UPLOAD_CONCURRENCY=2
```

(`AWS_REGION=loca` there is apparently another bug.)

**Comment by IlyaSemenov** [comment]
Perhaps this can be worked around by improving `wal-e-wal-fetch.sh` to pull S3_HOST from AWS_ENDPOINT for non-AWS endpoints. I'll come up with the PR.

**Comment by FxKu** [comment]
Closing this one as it got fixed in Spilo.

**Comment by IlyaSemenov** [comment]
FWIW, the problem ("Environment set by pod_environment_configmap not used in restore_script.sh") is still relevant and not fixed in Spilo. I managed to address *my specific use case* by updating Spilo to properly use what's passed. But it's still not possible to push any additional environment to restore_script with `pod_environment_configmap`.

I agree that it's not relevant to *this repo* though, as it's not operator's business but Spilo's.
